[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#7f7f7f"
blue = "#5c5cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000ee"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[debug]
persistent_logging = true

[font]
size = 13

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "Liberation Mono"
style = "Normal"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 75
lines = 25
